#!/usr/bin/env python

import optparse
from libwbook import inputing, searching, outputing

def _parse_args():
    parser = optparse.OptionParser()
    parser.add_option("-d", "--dict")
    parser.add_option("-b", "--back", type="int")
    parser.add_option("-f", "--forth", type="int")
    parser.set_defaults(back=3, forth=15,
            dict="/opt/wbook/share/wbook/final.eng")

    return parser.parse_args()

def main():
    options, args = _parse_args()
    line = " ".join(args)

    reader = inputing.Reader(line)
    search = searching.Search(options)
    outputer = outputing.Outputer(options)
    try:
        while True:
            line = reader.read_line()
            results = search.find(line)
            outputer.display(results)
            outputer.say(line)

    except EOFError:
        print "OK, bye."


if __name__ == "__main__":
    main()
